title: jblas
email: jblas-users@googlegroups.com
description: Linear Algebra for Java

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jblas.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jblas-project
github_username:  jblas-project

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

